GROUP AND SUMMARIZING

Summarizing the median life expectancy
```{r}
gapminder %>% 
  summarize(medianLifeExp = median(lifeExp)) #Calcula la mediana del set de datos
#Filter for 1957 then summarize the median life expectancy
gapminder %>% 
  filter(year == 1957) %>% 
  summarize(medianLifeExp = median(lifeExp)) #Calcula la mediana del set de datos

gapminder %>% 
  filter(year == 1957) %>% 
  summarize(medianLifeExp = median(lifeExp), maxgdpPercap = max(gdpPercap))

```
The group_by verb
```{r}
gapminder %>% 
  group_by(year) %>% 
  summarize(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))
```
Summarizing by continent
```{r}
gapminder %>% 
  filter(year == 1957) %>% 
  group_by(continent) %>% 
  summarize(medianLifeExp = median(lifeExp), maxGdpPercapt = max(gdpPercap))
```
Summarizing by continent and year
```{r}
gapminder %>% 
  group_by(continent, year) %>% 
  summarize(medianLifeExp = median(lifeExp), maxGdpPercapt = max(gdpPercap))
```
Visualizing median life expectancy over timer
```{r}
by_year <- gapminder %>% 
  group_by(year) %>% 
  summarize(medianGdpPercap = median(gdpPercap))
by_year
ggplot(by_year, aes(x=year, y=medianGdpPercap)) +
  geom_line()
```
```{r}
by_year_continent <- gapminder %>% 
  group_by(year, continent) %>% 
  summarize(medianGdpPercap = median(gdpPercap))
by_year_continent
ggplot(by_year_continent, aes(x=year, y=medianGdpPercap, color=continent)) +
  geom_line()
```
BAR PLOT

Visualizing median GDP per catita by continent
```{r}
gapminder
by_continent <- gapminder %>% 
  filter(year==1952) %>% 
  group_by(continent) %>% 
  summarize(medianGdpPercap = median(gdpPercap))
by_continent
ggplot(by_continent, aes(x=continent, y=medianGdpPercap)) +
  geom_col()
```
Visualizing GDP per capita by country in Oceania
```{r}

oceania_1952 <- gapminder %>% 
  filter(continent == "Oceania", year == 1952)
oceania_1952
ggplot(oceania_1952, aes(x=country, y=gdpPercap)) +
  geom_col()
```

